/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "A", "Ilkom"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "B", "Pilkom"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "C", "Komunikasi"));
        // Set Table
        TabelHasil.setModel(setTable());
        // Hide Delete button
        deleteButton.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai", "Prodi"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[4];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();
            row[3] = listMhs.get(i).getProdi();
            dataTabel.addRow(row);
        }

        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = TextFieldNIM.getText();
        String nama = TextFieldNama.getText();
        String nilai = TextFieldNilai.getText();
        String prodi = TextFieldProdi.getText();
        
        listMhs.add(new Mahasiswa(nim, nama, nilai, prodi));
        //Update Table
        TabelHasil.setModel(setTable());

        System.out.println("Insert Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
    }

    public void updateData() {
        // Get Data
        String nim = TextFieldNIM.getText();
        String nama = TextFieldNama.getText();
        String nilai = TextFieldNilai.getText();
        String prodi = TextFieldProdi.getText();
        //System.out.println(nim + nama + nilai);

        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
        listMhs.get(selectedID).setProdi(prodi);
        //Update Table
        TabelHasil.setModel(setTable());
        
        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
    }

    public void deleteData() {
        int i = 0;
        int found = 0;
        int index = 0;
        int record = listMhs.size();
        String nim = TextFieldNIM.getText();
        String nama = TextFieldNama.getText();
        String nilai = TextFieldNilai.getText();
        String prodi = TextFieldProdi.getText();
        while ((i < record) && (found == 0)){
            if((listMhs.get(i).getNim().equals(nim)) && (listMhs.get(i).getNama().equals(nama)) && (listMhs.get(i).getNilai().equals(nilai)) && (listMhs.get(i).getProdi().equals(prodi))) {
                found = 1;
                index = i;
            }
            i++;
        }
        
        if (found == 1) {
            ((DefaultTableModel)TabelHasil.getModel()).removeRow(index);
            listMhs.remove(index);
            System.out.println("Delete Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } else JOptionPane.showMessageDialog(null, "Data gagal dihapus karena textform sudah berubah!");
        
        
    }
    
    private void clearText(){
        TextFieldNIM.setText("");
        TextFieldNama.setText("");
        TextFieldNilai.setText("");
        TextFieldProdi.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingMahasiswa = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        TextFieldNIM = new javax.swing.JTextField();
        LabelNIM = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        LabelNilai = new javax.swing.JLabel();
        TextFieldNilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelHasil = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        LabelProdi = new javax.swing.JLabel();
        TextFieldProdi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeadingMahasiswa.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        HeadingMahasiswa.setText("Daftar Mahasiswa");

        addButton.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        TextFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNIMActionPerformed(evt);
            }
        });

        LabelNIM.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        LabelNIM.setText("NIM");

        LabelNama.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        LabelNama.setText("Nama");

        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });

        LabelNilai.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        LabelNilai.setText("Nilai");

        TextFieldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNilaiActionPerformed(evt);
            }
        });

        TabelHasil.setAutoCreateRowSorter(true);
        TabelHasil.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        TabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelHasil.setUpdateSelectionOnSort(false);
        TabelHasil.setVerifyInputWhenFocusTarget(false);
        TabelHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelHasil);

        deleteButton.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        LabelProdi.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        LabelProdi.setText("Prodi");

        TextFieldProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldProdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HeadingMahasiswa)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelProdi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNIM)
                                    .addGap(55, 55, 55)
                                    .addComponent(TextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelNilai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(deleteButton)
                            .addComponent(cancelButton))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(HeadingMahasiswa)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNIM)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama)
                    .addComponent(cancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNilai)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProdi)
                    .addComponent(TextFieldProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNIMActionPerformed

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void TextFieldNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNilaiActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String nim = TextFieldNIM.getText();
        String nama = TextFieldNama.getText();
        String nilai = TextFieldNilai.getText();
        String prodi = TextFieldProdi.getText();
        
        if (nim.isEmpty() || nama.isEmpty() || nilai.isEmpty() || prodi.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        } else {
            if (isUpdate == false)
                insertData();
            else {
                updateData();
                addButton.setText("Add");
                deleteButton.setVisible(false);
                this.isUpdate = false;
            }
            clearText();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void TabelHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelHasilMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = TabelHasil.getSelectedRow();
        String selectedNim = (TabelHasil.getModel().getValueAt(row, 0).toString());
        String selectedNama = (TabelHasil.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (TabelHasil.getModel().getValueAt(row, 2).toString());
        String selectedProdi = (TabelHasil.getModel().getValueAt(row, 3).toString());
        
        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        TextFieldNIM.setText(selectedNim);
        TextFieldNama.setText(selectedNama);
        TextFieldNilai.setText(selectedNilai);
        TextFieldProdi.setText(selectedProdi);
        
        addButton.setText("Update");
        deleteButton.setVisible(true);
    }//GEN-LAST:event_TabelHasilMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            clearText();
            addButton.setText("Add");
            deleteButton.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clearText();
        addButton.setText("Add");
        deleteButton.setVisible(false);
        this.isUpdate = false;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void TextFieldProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldProdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingMahasiswa;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNilai;
    private javax.swing.JLabel LabelProdi;
    private javax.swing.JTable TabelHasil;
    private javax.swing.JTextField TextFieldNIM;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNilai;
    private javax.swing.JTextField TextFieldProdi;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
